apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stakater-mvn-lint-code
  labels:
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  steps:
    - image: 'maven:3.8.6-openjdk-11-slim'
      name: code-lint
      script: |
        if [ -f "pom.xml" ]
        then
         mvn checkstyle:check
        else
         echo "No maven project found"
        fi
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
    
